### ISSUE TITLE
Downcasting in `local_[mul|div]_switch_sink` rewrite

### ISSUE THREAD

**Issue by cpaniaguam** [pymc-devs/pytensor#1037]
### Describe the issue:

When building a `pytensor.function` with objects of the same type (`float64` in this case) an "error" is _reported_ (no "real" error is produced as program execution is not stopped). The message suggests a failure to cast a `Matrix(float32) (of Variable Switch.0)` to `Matrix(float64)`.

The MWE is most of a module from the [`hssm` package ](https://github.com/lnccbrown/HSSM/). Besides `pytensor`, it requires `numpy`, `pandas`, and `pymc`.

### Reproducable code example:

```python
"""Reproduce reported "error" in test_likelihoods.py from the hssm package.

For more about the hssm package, see https://github.com/lnccbrown/HSSM/

In particular, the error is reported in the `test_analytical_gradient` test.

Most of the hssm.likelihoods.analytical module is included here to reproduce the error, which is shown below:


<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> Cannot convert Type Matrix(float32, shape=(2, 3988)) (of Variable Switch.0) into Type Matrix(float64, shape=(2, 3988)). You can try to manually convert Switch.0 into a Matrix(float64, shape=(2, 3988)). local_mul_switch_sink
ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: local_mul_switch_sink
ERROR (pytensor.graph.rewriting.basic): node: Mul(Eq.0, Switch.0)
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last)
"""

import numpy as np
import pandas as pd
import pymc as pm
import pytensor
import pytensor.tensor as pt
from pytensor.compile.nanguardmode import NanGuardMode

π = np.pi
τ = 2 * π
sqrt_τ = pt.sqrt(τ)
log_π = pt.log(π)
log_τ = pt.log(τ)
log_4 = pt.log(4)

LOGP_LB = pm.floatX(-66.1)


def _max(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return pt.max(pt.stack([a, b]), axis=0)


def k_small(rt: np.ndarray, err: float) -> np.ndarray:  # noqa: D103
    sqrt_rt = pt.sqrt(rt)
    log_rt = pt.log(rt)
    rt_log_2_sqrt_τ_rt_times_2 = rt * (log_4 + log_τ + log_rt)

    ks = 2 + pt.sqrt(-err * rt_log_2_sqrt_τ_rt_times_2)
    ks = _max(ks, sqrt_rt + 1)

    condition = 2 * sqrt_τ * sqrt_rt * err < 1
    ks = pt.switch(condition, ks, 2)

    return ks


def k_large(rt: np.ndarray, err: float) -> np.ndarray:  # noqa: D103
    log_rt = pt.log(rt)
    sqrt_rt = pt.sqrt(rt)
    log_err = pt.log(err)

    π_rt_err = π * rt * err
    π_sqrt_rt = π * sqrt_rt

    kl = pt.sqrt(-2 * (log_π + log_err + log_rt)) / π_sqrt_rt
    kl = _max(kl, 1.0 / pt.sqrt(π_sqrt_rt))
    kl = pt.switch(π_rt_err < 1, kl, 1.0 / π_sqrt_rt)

    return kl


def compare_k(rt: np.ndarray, err: float) -> np.ndarray:  # noqa: D103
    ks = k_small(rt, err)
    kl = k_large(rt, err)

    return ks < kl


def get_ks(k_terms: int, fast: bool) -> np.ndarray:  # noqa: D103
    ks = (
        pt.arange(-pt.floor((k_terms - 1) / 2), pt.ceil((k_terms - 1) / 2) + 1)
        if fast
        else pt.arange(1, k_terms + 1).reshape((-1, 1))
    )

    return ks.astype(pytensor.config.floatX)


def ftt01w_fast(tt: np.ndarray, w: float, k_terms: int) -> np.ndarray:  # noqa: D103
    # Slightly changed the original code to mimic the paper and
    # ensure correctness
    k = get_ks(k_terms, fast=True)

    # A log-sum-exp trick is used here
    y = w + 2 * k.reshape((-1, 1))
    r = -pt.power(y, 2) / (2 * tt)
    c = pt.max(r, axis=0)
    p = pt.exp(c) * pt.sum(y * pt.exp(r - c), axis=0)
    # Normalize p
    p = p / pt.sqrt(2 * π * pt.power(tt, 3))

    return p


def ftt01w_slow(tt: np.ndarray, w: float, k_terms: int) -> np.ndarray:  # noqa: D103
    k = get_ks(k_terms, fast=False)
    y = k * pt.sin(k * π * w)
    r = -pt.power(k, 2) * pt.power(π, 2) * tt / 2
    p = pt.sum(y * pt.exp(r), axis=0) * π

    return p


def ftt01w(  # noqa: D103
    rt: np.ndarray,
    a: float,
    w: float,
    err: float = 1e-7,
    k_terms: int = 10,
) -> np.ndarray:
    tt = rt / a**2.0

    lambda_rt = compare_k(tt, err)

    p_fast = ftt01w_fast(tt, w, k_terms)
    p_slow = ftt01w_slow(tt, w, k_terms)

    p = pt.switch(lambda_rt, p_fast, p_slow)

    return p


def main():  # noqa: D103
    cav_data = pd.read_csv(
        "https://raw.githubusercontent.com/lnccbrown/HSSM/refs/heads/main/src/hssm/datasets/cavanagh_theta_nn.csv"
    )
    cav_data = cav_data[["rt", "response"]].values

    nan_guard_mode = NanGuardMode(
        nan_is_error=True, inf_is_error=True, big_is_error=False
    )

    v = pt.dvector()
    a = 2 * pt.dvector()
    z = pt.dvector()
    t = pt.dvector()

    epsilon: float = 1e-15

    data = pt.reshape(cav_data, (-1, 2)).astype(pytensor.config.floatX)
    rt = pt.abs(data[:, 0])
    response = data[:, 1]
    flip = response > 0

    v_flipped = pt.switch(flip, -v, v)
    z_flipped = pt.switch(flip, 1 - z, z)

    rt = rt - t
    negative_rt = rt < 0
    rt = pt.switch(negative_rt, epsilon, rt)

    p = pt.maximum(ftt01w(rt, a, z_flipped, epsilon, 20), pt.exp(LOGP_LB))

    logp = pt.log(p)
    loga = pt.log(a)
    alt = logp - v_flipped * a * z_flipped - (v_flipped**2 * rt / 2.0) - 2.0 * loga

    logp = pt.where(
        rt <= epsilon,
        LOGP_LB,
        alt,
    )

    grad = pt.grad(logp.sum(), wrt=[v, a, z, t])

    # check everything is of type float64
    assert all([x.dtype == "float64" for x in grad])
    assert all([x.dtype == "float64" for x in [a, v, z, t]])

    pytensor.function(
        [v, a, z, t],
        grad,
        mode=nan_guard_mode,
    )


if __name__ == "__main__":
    main()
```

### Error message:

```shell
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> Cannot convert Type Matrix(float32, shape=(2, 3988)) (of Variable Switch.0) into Type Matrix(float64, shape=(2, 3988)). You can try to manually convert Switch.0 into a Matrix(float64, shape=(2, 3988)). local_mul_switch_sink
ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: local_mul_switch_sink
ERROR (pytensor.graph.rewriting.basic): node: Mul(Eq.0, Switch.0)
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/graph/rewriting/basic.py", line 1955, in process_node
    fgraph.replace_all_validate_remove(  # type: ignore
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/graph/features.py", line 627, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason=reason, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/graph/features.py", line 572, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False, **kwargs)
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/graph/fg.py", line 498, in replace
    new_var = var.type.filter_variable(new_var, allow_convert=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/tensor/type.py", line 278, in filter_variable
    raise TypeError(
TypeError: Cannot convert Type Matrix(float32, shape=(2, 3988)) (of Variable Switch.0) into Type Matrix(float64, shape=(2, 3988)). You can try to manually convert Switch.0 into a Matrix(float64, shape=(2, 3988)).

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> Cannot convert Type Matrix(float32, shape=(2, 3988)) (of Variable Switch.0) into Type Matrix(float64, shape=(2, 3988)). You can try to manually convert Switch.0 into a Matrix(float64, shape=(2, 3988)). local_mul_switch_sink
ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: local_mul_switch_sink
ERROR (pytensor.graph.rewriting.basic): node: Mul(Eq.0, Switch.0)
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/graph/rewriting/basic.py", line 1955, in process_node
    fgraph.replace_all_validate_remove(  # type: ignore
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/graph/features.py", line 627, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason=reason, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/graph/features.py", line 572, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False, **kwargs)
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/graph/fg.py", line 498, in replace
    new_var = var.type.filter_variable(new_var, allow_convert=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cpaniaguam/.cache/pypoetry/virtualenvs/hssm-XZfoo1Lc-py3.11/lib/python3.11/site-packages/pytensor/tensor/type.py", line 278, in filter_variable
    raise TypeError(
TypeError: Cannot convert Type Matrix(float32, shape=(2, 3988)) (of Variable Switch.0) into Type Matrix(float64, shape=(2, 3988)). You can try to manually convert Switch.0 into a Matrix(float64, shape=(2, 3988)).
```

### PyTensor version information:

pytensor==2.25.4
Python 3.11.8
OS: Ubuntu 22.04.3 LTS
Installed via poetry (see the [hssm package repo](https://github.com/lnccbrown/HSSM/) )

<details>
floatX ({'float64', 'float16', 'float32'}) 
    Doc:  Default floating-point precision for python casts.

Note: float16 support is experimental, use at your own risk.
    Value:  float64

warn_float64 ({'pdb', 'ignore', 'warn', 'raise'}) 
    Doc:  Do an action when a tensor variable with float64 dtype is created.
    Value:  ignore

pickle_test_value (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59df9390>>) 
    Doc:  Dump test values while pickling model. If True, test values will be dumped with model.
    Value:  True

cast_policy ({'numpy+floatX', 'custom'}) 
    Doc:  Rules for implicit type casting
    Value:  custom

device (cpu)
    Doc:  Default device for computations. only cpu is supported for now
    Value:  cpu

conv__assert_shape (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59df92d0>>) 
    Doc:  If True, AbstractConv* ops will verify that user-provided shapes match the runtime shapes (debugging option, may slow down compilation)
    Value:  False

print_global_stats (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59df9210>>) 
    Doc:  Print some global statistics (time spent) at the end
    Value:  False

unpickle_function (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5af11c50>>) 
    Doc:  Replace unpickled PyTensor functions with None. This is useful to unpickle old graphs that pickled them when it shouldn't
    Value:  True

<pytensor.configparser.ConfigParam object at 0x7f1b5adcabd0>
    Doc:  Default compilation mode
    Value:  Mode

cxx (<class 'str'>) 
    Doc:  The C++ compiler to use. Currently only g++ is supported, but supporting additional compilers should not be too difficult. If it is empty, no C++ code is compiled.
    Value:  /usr/bin/g++

linker ({'c', 'vm_nogc', 'c|py', 'py', 'c|py_nogc', 'vm', 'cvm', 'cvm_nogc'}) 
    Doc:  Default linker used if the pytensor flags mode is Mode
    Value:  cvm

allow_gc (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfa750>>) 
    Doc:  Do we default to delete intermediate results during PyTensor function calls? Doing so lowers the memory requirement, but asks that we reallocate memory at the next function call. This is implemented for the default linker, but may not work for all linkers.
    Value:  True

optimizer ({'None', 'o2', 'o4', 'o1', 'fast_compile', 'merge', 'fast_run', 'o3', 'unsafe'}) 
    Doc:  Default optimizer. If not None, will use this optimizer with the Mode
    Value:  o4

optimizer_verbose (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b8ddfaad0>>) 
    Doc:  If True, we print all optimization being applied
    Value:  False

on_opt_error ({'pdb', 'ignore', 'warn', 'raise'}) 
    Doc:  What to do when an optimization crashes: warn and skip it, raise the exception, or fall into the pdb debugger.
    Value:  warn

nocleanup (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5a442910>>) 
    Doc:  Suppress the deletion of code files that did not compile cleanly
    Value:  False

on_unused_input ({'ignore', 'warn', 'raise'}) 
    Doc:  What to do if a variable in the 'inputs' list of  pytensor.function() is not used in the graph.
    Value:  raise

gcc__cxxflags (<class 'str'>) 
    Doc:  Extra compiler flags for gcc
    Value:  

cmodule__warn_no_version (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfab90>>) 
    Doc:  If True, will print a warning when compiling one or more Op with C code that can't be cached because there is no c_code_cache_version() function associated to at least one of those Ops.
    Value:  False

cmodule__remove_gxx_opt (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfac90>>) 
    Doc:  If True, will remove the -O* parameter passed to g++.This is useful to debug in gdb modules compiled by PyTensor.The parameter -g is passed by default to g++
    Value:  False

cmodule__compilation_warning (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5ae4e2d0>>) 
    Doc:  If True, will print compilation warnings.
    Value:  False

cmodule__preload_cache (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfad50>>) 
    Doc:  If set to True, will preload the C module cache at import time
    Value:  False

cmodule__age_thresh_use (<class 'int'>) 
    Doc:  In seconds. The time after which PyTensor won't reuse a compile c module.
    Value:  2073600

cmodule__debug (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfaf10>>) 
    Doc:  If True, define a DEBUG macro (if not exists) for any compiled C code.
    Value:  False

compile__wait (<class 'int'>) 
    Doc:  Time to wait before retrying to acquire the compile lock.
    Value:  5

compile__timeout (<class 'int'>) 
    Doc:  In seconds, time that a process will wait before deciding to
    override an existing lock. An override only happens when the existing
    lock is held by the same owner *and* has not been 'refreshed' by this
    owner for more than this period. Refreshes are done every half timeout
    period for running processes.
    Value:  120

tensor__cmp_sloppy (<class 'int'>) 
    Doc:  Relax pytensor.tensor.math._allclose (0) not at all, (1) a bit, (2) more
    Value:  0

lib__amdlibm (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfb0d0>>) 
    Doc:  Use amd's amdlibm numerical library
    Value:  False

tensor__insert_inplace_optimizer_validate_nb (<class 'int'>) 
    Doc:  -1: auto, if graph have less then 500 nodes 1, else 10
    Value:  -1

traceback__limit (<class 'int'>) 
    Doc:  The number of stack to trace. -1 mean all.
    Value:  8

traceback__compile_limit (<class 'int'>) 
    Doc:  The number of stack to trace to keep during compilation. -1 mean all. If greater then 0, will also make us save PyTensor internal stack trace.
    Value:  0

warn__ignore_bug_before ({'0.8', 'all', '1.0.2', '1.0.5', '0.7', '0.4', 'None', '1.0.1', '0.3', '0.8.1', '1.0.4', '0.6', '0.9', '1.0', '0.8.2', '1.0.3', '0.5', '0.4.1', '0.10'}) 
    Doc:  If 'None', we warn about all PyTensor bugs found by default. If 'all', we don't warn about PyTensor bugs found by default. If a version, we print only the warnings relative to PyTensor bugs found after that version. Warning for specific bugs can be configured with specific [warn] flags.
    Value:  0.9

exception_verbosity ({'high', 'low'}) 
    Doc:  If 'low', the text of exceptions will generally refer to apply nodes with short names such as Elemwise{add_no_inplace}. If 'high', some exceptions will also refer to apply nodes with long descriptions  like:
        A. Elemwise{add_no_inplace}
                B. log_likelihood_v_given_h
                C. log_likelihood_h
    Value:  low

print_test_value (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfa650>>) 
    Doc:  If 'True', the __eval__ of an PyTensor variable will return its test_value when this is available. This has the practical consequence that, e.g., in debugging `my_var` will print the same as `my_var.tag.test_value` when a test value is defined.
    Value:  False

compute_test_value ({'off', 'raise', 'warn', 'pdb', 'ignore'}) 
    Doc:  If 'True', PyTensor will run each op at graph build time, using Constants, SharedVariables and the tag 'test_value' as inputs to the function. This helps the user track down problems in the graph before it gets optimized.
    Value:  off

compute_test_value_opt ({'off', 'raise', 'warn', 'pdb', 'ignore'}) 
    Doc:  For debugging PyTensor optimization only. Same as compute_test_value, but is used during PyTensor optimization
    Value:  off

check_input (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b8abd2a90>>) 
    Doc:  Specify if types should check their input in their C code. It can be used to speed up compilation, reduce overhead (particularly for scalars) and reduce the number of generated C files.
    Value:  True

NanGuardMode__nan_is_error (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5af11d50>>) 
    Doc:  Default value for nan_is_error
    Value:  True

NanGuardMode__inf_is_error (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b8da1aa90>>) 
    Doc:  Default value for inf_is_error
    Value:  True

NanGuardMode__big_is_error (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfa2d0>>) 
    Doc:  Default value for big_is_error
    Value:  True

NanGuardMode__action ({'pdb', 'warn', 'raise'}) 
    Doc:  What NanGuardMode does when it finds a problem
    Value:  raise

DebugMode__patience (<class 'int'>) 
    Doc:  Optimize graph this many times to detect inconsistency
    Value:  10

DebugMode__check_c (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfa190>>) 
    Doc:  Run C implementations where possible
    Value:  True

DebugMode__check_py (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfb350>>) 
    Doc:  Run Python implementations where possible
    Value:  True

DebugMode__check_finite (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5af08810>>) 
    Doc:  True -> complain about NaN/Inf results
    Value:  True

DebugMode__check_strides (<class 'int'>) 
    Doc:  Check that Python- and C-produced ndarrays have same strides. On difference: (0) - ignore, (1) warn, or (2) raise error
    Value:  0

DebugMode__warn_input_not_reused (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5ada2950>>) 
    Doc:  Generate a warning when destroy_map or view_map says that an op works inplace, but the op did not reuse the input for its output.
    Value:  True

DebugMode__check_preallocated_output (<class 'str'>) 
    Doc:  Test thunks with pre-allocated memory as output storage. This is a list of strings separated by ":". Valid values are: "initial" (initial storage in storage map, happens with Scan),"previous" (previously-returned memory), "c_contiguous", "f_contiguous", "strided" (positive and negative strides), "wrong_size" (larger and smaller dimensions), and "ALL" (all of the above).
    Value:  

DebugMode__check_preallocated_output_ndim (<class 'int'>) 
    Doc:  When testing with "strided" preallocated output memory, test all combinations of strides over that number of (inner-most) dimensions. You may want to reduce that number to reduce memory or time usage, but it is advised to keep a minimum of 2.
    Value:  4

profiling__time_thunks (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfb590>>) 
    Doc:  Time individual thunks when profiling
    Value:  True

profiling__n_apply (<class 'int'>) 
    Doc:  Number of Apply instances to print by default
    Value:  20

profiling__n_ops (<class 'int'>) 
    Doc:  Number of Ops to print by default
    Value:  20

profiling__output_line_width (<class 'int'>) 
    Doc:  Max line width for the profiling output
    Value:  512

profiling__min_memory_size (<class 'int'>) 
    Doc:  For the memory profile, do not print Apply nodes if the size
                 of their outputs (in bytes) is lower than this threshold
    Value:  1024

profiling__min_peak_memory (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfb810>>) 
    Doc:  The min peak memory usage of the order
    Value:  False

profiling__destination (<class 'str'>) 
    Doc:  File destination of the profiling output
    Value:  stderr

profiling__debugprint (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5af21cd0>>) 
    Doc:  Do a debugprint of the profiled functions
    Value:  False

profiling__ignore_first_call (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfb950>>) 
    Doc:  Do we ignore the first call of an PyTensor function.
    Value:  False

on_shape_error ({'warn', 'raise'}) 
    Doc:  warn: print a warning and use the default value. raise: raise an error
    Value:  warn

openmp (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59dfbb50>>) 
    Doc:  Allow (or not) parallel computation on the CPU with OpenMP. This is the default value used when creating an Op that supports OpenMP parallelization. It is preferable to define it via the PyTensor configuration file ~/.pytensorrc or with the environment variable PYTENSOR_FLAGS. Parallelization is only done for some operations that implement it, and even for operations that implement parallelism, each operation is free to respect this flag or not. You can control the number of threads used with the environment variable OMP_NUM_THREADS. If it is set to 1, we disable openmp in PyTensor by default.
    Value:  False

openmp_elemwise_minsize (<class 'int'>) 
    Doc:  If OpenMP is enabled, this is the minimum size of vectors for which the openmp parallelization is enabled in element wise ops.
    Value:  200000

optimizer_excluding (<class 'str'>) 
    Doc:  When using the default mode, we will remove optimizer with these tags. Separate tags with ':'.
    Value:  

optimizer_including (<class 'str'>) 
    Doc:  When using the default mode, we will add optimizer with these tags. Separate tags with ':'.
    Value:  

optimizer_requiring (<class 'str'>) 
    Doc:  When using the default mode, we will require optimizer with these tags. Separate tags with ':'.
    Value:  

optdb__position_cutoff (<class 'float'>) 
    Doc:  Where to stop earlier during optimization. It represent the position of the optimizer where to stop.
    Value:  inf

optdb__max_use_ratio (<class 'float'>) 
    Doc:  A ratio that prevent infinite loop in EquilibriumGraphRewriter.
    Value:  8.0

cycle_detection ({'regular', 'fast'}) 
    Doc:  If cycle_detection is set to regular, most inplaces are allowed,but it is slower. If cycle_detection is set to faster, less inplacesare allowed, but it makes the compilation faster.The interaction of which one give the lower peak memory usage iscomplicated and not predictable, so if you are close to the peakmemory usage, triyng both could give you a small gain.
    Value:  regular

check_stack_trace ({'off', 'warn', 'log', 'raise'}) 
    Doc:  A flag for checking the stack trace during the optimization process. default (off): does not check the stack trace of any optimization log: inserts a dummy stack trace that identifies the optimizationthat inserted the variable that had an empty stack trace.warn: prints a warning if a stack trace is missing and also a dummystack trace is inserted that indicates which optimization insertedthe variable that had an empty stack trace.raise: raises an exception if a stack trace is missing
    Value:  off

metaopt__verbose (<class 'int'>) 
    Doc:  0 for silent, 1 for only warnings, 2 for full output withtimings and selected implementation
    Value:  0

unittests__rseed (<class 'str'>) 
    Doc:  Seed to use for randomized unit tests. Special value 'random' means using a seed of None.
    Value:  666

warn__round (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59e000d0>>) 
    Doc:  Warn when using `tensor.round` with the default mode. Round changed its default from `half_away_from_zero` to `half_to_even` to have the same default as NumPy.
    Value:  False

profile (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5aeb1f50>>) 
    Doc:  If VM should collect profile information
    Value:  False

profile_optimizer (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5ae4ed90>>) 
    Doc:  If VM should collect optimizer profile information
    Value:  False

profile_memory (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5a399d10>>) 
    Doc:  If VM should collect memory profile information and print it
    Value:  False

<pytensor.configparser.ConfigParam object at 0x7f1b5ae96110>
    Doc:  Useful only for the VM Linkers. When lazy is None, auto detect if lazy evaluation is needed and use the appropriate version. If the C loop isn't being used and lazy is True, use the Stack VM; otherwise, use the Loop VM.
    Value:  None

numba__vectorize_target ({'parallel', 'cuda', 'cpu'}) 
    Doc:  Default target for numba.vectorize.
    Value:  cpu

numba__fastmath (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59e00350>>) 
    Doc:  If True, use Numba's fastmath mode.
    Value:  True

numba__cache (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b5a442950>>) 
    Doc:  If True, use Numba's file based caching.
    Value:  True

compiledir_format (<class 'str'>) 
    Doc:  Format string for platform-dependent compiled module subdirectory
(relative to base_compiledir). Available keys: device, gxx_version,
hostname, numpy_version, platform, processor, pytensor_version,
python_bitwidth, python_int_bitwidth, python_version, short_platform.
Defaults to compiledir_%(short_platform)s-%(processor)s-
%(python_version)s-%(python_bitwidth)s.
    Value:  compiledir_%(short_platform)s-%(processor)s-%(python_version)s-%(python_bitwidth)s

<pytensor.configparser.ConfigParam object at 0x7f1b5ae27910>
    Doc:  platform-independent root directory for compiled modules
    Value:  /home/cpaniaguam/.pytensor

<pytensor.configparser.ConfigParam object at 0x7f1b59e00c90>
    Doc:  platform-dependent cache directory for compiled modules
    Value:  /home/cpaniaguam/.pytensor/compiledir_Linux-5.15-microsoft-standard-WSL2-x86_64-with-glibc2.35-x86_64-3.11.8-64

blas__ldflags (<class 'str'>) 
    Doc:  lib[s] to include for [Fortran] level-3 blas implementation
    Value:  -lmkl_core -lmkl_rt -lmkl_intel_thread -liomp5 -lpthread -Wl,-rpath,/home/cpaniaguam/.pyenv/versions/3.11.8/lib

blas__check_openmp (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b59ac0a90>>) 
    Doc:  Check for openmp library conflict.
WARNING: Setting this to False leaves you open to wrong results in blas-related operations.
    Value:  True

scan__allow_gc (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b2185b350>>) 
    Doc:  Allow/disallow gc inside of Scan (default: False)
    Value:  False

scan__allow_output_prealloc (<bound method BoolParam._apply of <pytensor.configparser.BoolParam object at 0x7f1b217ff310>>) 
    Doc:  Allow/disallow memory preallocation for outputs inside of scan (default: True)
    Value:  True
</details>

### Context for the issue:

The HSSM package is trusted by many researchers in the computational cognitive and psychological sciences.  The reported bug could erode that trust and affect the reputation of both HSSM's and PyTensor's.

**Comment by ricardoV94** [comment]
@cpaniaguam thanks for the reproducible example. #1059 should fix it
