### ISSUE TITLE
Organize Aesara downstreamed PRs better

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#115]
### Description

Can we automatically add the label: "Aesara downstream", and add those PRs in a separate section of the automatic release notes?

More importantly, can we make the automatic release notes reference the original author and not the person who performed the downstream PR? I had to do this manually in https://github.com/pymc-devs/pytensor/releases/tag/rel-2.8.11

CC @twiecki @michaelosthege

**Comment by michaelosthege** [comment]
This was addressed by #117

![image](https://user-images.githubusercontent.com/5894642/207972154-2258e575-5b61-41fd-819d-ca455b13db63.png)

**Comment by ricardoV94** [comment]
Would still be worth to check if we can get the automatic release notes to mention the original authors
