### ISSUE TITLE
Remove MPI Support?

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#119]
### Description

There is MPI support that we do not test, and do not use, should we remove it now? The implementation is not very complicated, but you need to take special care of how you make linker.
<img width="687" alt="image" src="https://user-images.githubusercontent.com/11705326/207310941-361d467a-fd13-468b-b26e-601048248ea3.png">
```
mpi_linker = OpWiseCLinker(schedule=mpi_scheduler)
mpi_mode = Mode(linker=mpi_linker)
```
https://github.com/pymc-devs/pytensor/blob/main/pytensor/tensor/io.py#L108

History reference
https://github.com/Theano/Theano/pull/916
https://github.com/Theano/Theano/pull/935

**Comment by ricardoV94** [comment]
Yeah I think we can remove it
