### ISSUE TITLE
Remove deprecated pytensor.tensor.nnet,signal

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#124]
### Description

```
python setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'version': '2.8.10+90.g10610f5bb', 'full-revisionid': '10610f5bbe8396cf51791f9c1c46884c75d1df57', 'dirty': False, 'error': None, 'date': '2022-12-13T23:53:11+0300'}
Version: 2.8.10+90.g10610f5bb
 full-revisionid: 10610f5bbe8396cf51791f9c1c46884c75d1df57
 dirty: False
 date: 2022-12-13T23:53:11+0300
```
I guess we consider to bump version very soon. This module was marked for removal in the nest release.

https://github.com/pymc-devs/pytensor/blob/21d723bd44749f540f86db451f6280753289c30d/pytensor/tensor/nnet/__init__.py#L4-L9

https://github.com/pymc-devs/pytensor/blob/21d723bd44749f540f86db451f6280753289c30d/pytensor/tensor/signal/conv.py#L14-L19

https://github.com/pymc-devs/pytensor/blob/21d723bd44749f540f86db451f6280753289c30d/pytensor/tensor/signal/pool.py#L22-L27

**Comment by ricardoV94** [comment]
We want to keep the conv2D around. We can drop the rest
