### ISSUE TITLE
Do we still need to support Sympy?

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#128]
### Description

https://github.com/pymc-devs/pytensor/blob/43d91d0a6efdf8f86abf5b6198ebaf074eff586c/pytensor/scalar/basic_sympy.py#L29

Tests pass so far

<img width="689" alt="image" src="https://user-images.githubusercontent.com/11705326/207575125-ad70b79c-2e49-4edd-b88d-0bef387bf211.png">

**Comment by twiecki** [comment]
No I don't think we should.
