### ISSUE TITLE
Follow a principled way to test ops

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#131]
### Description

Pytorch does this to automate test suite and their implementation for testing is relatively concise
* You create example inputs for the and reference Op once and there is a principled way to assert implementation is working
https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/opinfo/core.py

**Comment by ricardoV94** [comment]
Can you elaborate what PyTorch is doing that we are not and should be doing?
