### ISSUE TITLE
Drop Python 3.7

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#155]
### Description

Due to pymc supports Python 3.8+ it makes no sense to keep Python 3.7 here

https://github.com/pymc-devs/pymc/blob/0de47bcdc674f085acc91dc341f4d74c74078d13/setup.py#L74

**Comment by ricardoV94** [comment]
The reason to keeping support is that Google Colab keeps lagging behind -.-

**Comment by ferrine** [comment]
How could it happen if pymc is already on 3.8?

**Comment by twiecki** [comment]
We made a special 3.7 release for colab.

**Comment by ricardoV94** [comment]
Colab is now on 3.8, we can drop :)

**Comment by ricardoV94** [comment]
Closed via #210
