### ISSUE TITLE
DOC: typo on sigmoid function description

### ISSUE THREAD

**Issue by guin0x** [pymc-devs/pytensor#156]
### Issue with current documentation:

In the [sigmoid function](https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.math.sigmoid.html) it should be  `(1 / (1 + exp(-x))` instead of ` (1 / (1 + exp(x))`. The relevant line is [this](https://github.com/pymc-devs/pytensor/blob/f4de2fd256a90457a53a82c986934d23c36a87ed/pytensor/tensor/math.py#L1419).

**Comment by twiecki** [comment]
@guin0x Want to do a PR?

**Comment by aseyboldt** [comment]
Fixed in #157, thanks again @guin0x
