### ISSUE TITLE
Implement `numpy.sign` equivalent

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#162]
### Description

This seems to be missing: https://numpy.org/doc/stable/reference/generated/numpy.sign.html

Something like this should work?

```python
def sign(x):
  return pt.switch(pt.eq(x, 0), 0, pt.switch(x > 0, 1, -1))
```

**Comment by Mayuresh0072** [comment]
@ricardoV94 @ynd @rpgoldman Hello, I want to work on this issue, please assign me. Thanks

**Comment by ricardoV94** [comment]
Feel free to open a PR to tackle it.

**Comment by sudarsan2k5** [comment]
I think we already have a `sgn` for the same purpose and we can rename that to `sign`
