### ISSUE TITLE
ENH: `Join` looses static shape information

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pytensor#163]
### Describe the issue:

A simple `pt.concatenate` of tensors with known static shapes could easily result in a static shape.

Currently it does not.

### Reproducable code example:

```python
def test_concatenate_static_shapes():
    a = pt.ones((2, 3))
    b = pt.ones((2, 5))
    c = pt.concatenate([a, b], axis=1)
    assert c.eval().shape == (2, 8)
    assert c.type.shape == (2, 8)
    pass
```

### Error message:

```shell
>       assert c.type.shape == (2, 8)
E       assert (None, None) == (2, 8)
E         At index 0 diff: None != 2
E         Full diff:
E         - (2, 8)
E         + (None, None)

tests\test_setsubtensor.py:103: AssertionError
```

### PyTensor version information:

main

**Comment by ricardoV94** [comment]
That's not a bug. It's fine for an Op to lose shape information. We can improve it of course.

Other parts of the library do assume shape is not lost (as some asserts in rewrites). Those are bugs.
