### ISSUE TITLE
ENH: Make (some) commonly used signatures accept items or collections

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pytensor#17]
### Link to a discussion

@ferrine and I discussed this in chat, related to #15.

PR #15 is about a function that took an item as an argument, but the PR changed the signature to take a collection.

Instead of switching from taking items to taking collections we considered options to take either:
1. With `def f(*items: T)` the backwards compatibility is maintained, but multiple items/collections can be passed like `f(a, b)` or `f(*abc)`.
2. With `def f(items: Union[T, Collection[T]])` the function can do an `isinstance(items, T)` check to convert to a collection internally while the calls can be `f(a)` or `f(abc)`.

The `*items` signature is not common in the codebase, therefore we concluded to favor option 2.

__Where this applies__

* The new `is_in_ancestors` from #15
* `pytensor.function` is an example that is already flexible in this way: 

https://github.com/pymc-devs/pytensor/blob/2f37b463e083220f5016f5f5973dbe397796a71d/pytensor/compile/function/__init__.py#L106-L109

* `FunctionGraph` currently takes only collections:

https://github.com/pymc-devs/pytensor/blob/2f37b463e083220f5016f5f5973dbe397796a71d/pytensor/graph/fg.py#L76-L77

### Before

```python
x = pt.dscalar("x")
y = x + 2

fg = FunctionGraph([x], [y])
```

### After

```python
x = pt.dscalar("x")
y = x + 2

fg = FunctionGraph(x, y)
```

**Comment by mjhajharia** [comment]
so do we want to go with the first option here?

**Comment by michaelosthege** [comment]
> so do we want to go with the first option here?

Yes, Max and I concluded that we prefer option 2

**Comment by ricardoV94** [comment]
I don't think either of these examples is commonly used that we need the extra flexibility. 

Also the FunctionGraph example is invalid. The proposed change is ambiguous as a FunctionGraph can have zero or more inputs and multiple outputs.

**Comment by ricardoV94** [comment]
I'm closing this issue because it's not actionable. I suggest opening issues for specific cases that should support the different types of inputs so that people know where to contribute.
