### ISSUE TITLE
Release pipeline broke because PyPI doesn't accept platform/version-specific Wheels

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pytensor#173]
### Description

https://github.com/pymc-devs/pytensor/actions/runs/3845904313/jobs/6550625819

https://stackoverflow.com/questions/59451069/binary-wheel-cant-be-uploaded-on-pypi-using-twine

**Comment by ferrine** [comment]
maybe indeed the answer from SO will help https://stackoverflow.com/a/59586096

**Comment by michaelosthege** [comment]
Yeah I saw that answer, but didn't understand _how_ to use these tools to do the job

However, I stopped investigating as I had to focus on other things

**Comment by cerrussell** [comment]
@michaelosthege I will help with this - just set up the same sort of thing for two other projects, so it's fresh in my mind...

**Comment by michaelosthege** [comment]
@cerrussell I suppose we need to expand the job matrix to Windows ans MacOS and then have some kind of command that combines all the wheels into one before uploading?

**Comment by cerrussell** [comment]
@michaelosthege The wheels aren't combined. I've modified the [workflow on my fork](https://github.com/cerrussell/pytensor/actions/workflows/pypi.yml) and am just trying to resolve some issues related to test dependencies.

**Comment by michaelosthege** [comment]
@cerrussell looks like you got it working in your last commit?

I you open a PR I'll be happy to get it over the finish line!

**Comment by michaelosthege** [comment]
In #183 we (accidentally) renamed the PyPI token/secret variable which failed the release pipeline at first.
I generated a new token and retried-the job.

`v2.9.1` is finally out on PyPI: https://github.com/pymc-devs/pytensor/actions/runs/3885025171/jobs/6630423337 🎉
