### ISSUE TITLE
Refactor `_print_name` for certain RVs?

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pytensor#204]
### Description

The names of some random variables are abbreviated when printing them or displaying them. It _could_ be a good idea to instead use distributions' full names to represent them with more clarity. For instance, see (reverted) PyMC [PR #6219](https://github.com/pymc-devs/pymc/pull/6219) for details.

Should we incorporate this change to PyTensor?

**Comment by ricardoV94** [comment]
Definitely
