### ISSUE TITLE
`get_scalar_constant` does not raise for homogenous non-scalar constants

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#226]
### Description

```python
import numpy as np
import pytensor as pt

pt.get_scalar_constant_value(pt.constant(np.zeros(5)))  # 0.0;  wrong!
pt.get_scalar_constant_value(pt.constant(np.arange(5)))  # raises NotScalarConstantError; correct
```

This makes this rewrite fail unnecessarily sometimes: https://github.com/pymc-devs/pytensor/blob/d7d20be24248537059732a3a7dca3f33499f4742/pytensor/tensor/rewriting/elemwise.py#L468-L536

**Comment by ricardoV94** [comment]
This led to a bug in one of the scan rewrites, fixing...

**Comment by ricardoV94** [comment]
This seems to be the explicit goal of this helper, in which case I think a better name should be given. Maybe something like `get_underlying_scalar_constant` or something that emphasizes we don't expect the output variables to be scalar +- only degenerate dims...

**Comment by shreyas3156** [comment]
Hi @ricardoV94, can we rename it to `get_underlying_scalar_constant` and add to the docstring that it is expected to have an output for both - variables with degenerate dims and homogenous non-scalar constants?

**Comment by ricardoV94** [comment]
@shreyas3156 that sounds good.

In addition we could add a `get_scalar_constant` that only works for scalar outputs (i.e., ndim=0). 

That could simply call `get_underlying_scalar_constant` after checking we are dealing with a scalar variable.

**Comment by shreyas3156** [comment]
To confirm I've understood it correctly,
 `get_scalar_constant` should check if we are working with a scalar variable (ndim = 0). If not, then it would call `get_underlying_scalar_constant` for non-scalar constants. Please correct me if I've missed something.

**Comment by ricardoV94** [comment]
If not scalar it should raise NotScalarConstantError directly. If it's a scalar it should then call the newly renamed "get_underlying_scalar_constant".

All existing references to `get_scalar_constant` should use the renamed function.

Does that make sense?

**Comment by shreyas3156** [comment]
Yes! Thank you for the clarification.
