### ISSUE TITLE
Allow string keys in `.eval`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#227]
### Description

`eval` is very useful for debugging, including interactive debugging during development. One issue is that required inputs must be passed by reference which is not always easy to do inside a given stack. 

I usually have to play with ancestors to get a hold of the input variable. Instead it would be neat if we can get it by name if a string is used as a key in `eval`

```python
import pytensor.tensor as pt

def create_expr():
  x = pt.scalar("x")
  y = pt.exp(x)
  return y

y = create_expr()
# Feature request:
y.eval({"x": 0})  # 1.0
```

If there are multiple variables with the same key name we could use the closest + warning or raise.

There is already a handy utility to find variables by name: https://pytensor.readthedocs.io/en/latest/library/graph/graph.html#pytensor.graph.basic.get_var_by_name

**Comment by Raj-Parekh24** [comment]
Hello @ricardoV94 ,

I am new to this project and want to make a contribution.

I am working on this issue. I have implemented a function that converts the dictionary with string keys to pytensor. The pytensor variable for the corresponding name is found using the function "get_var_by_name".

While calling the function we have to pass list of variables under graph parameter name.

I have a doubt that in class method which list of method do we have to pass.

Below attaching a function for reference, please help me.

**Comment by Raj-Parekh24** [comment]
`def convert_string_keys_to_pytensor_variables(self, inputs_to_values):
        process_input_to_values = {}
        for i in inputs_to_values:
            if isinstance(i, str):
                nodes_with_matching_names = get_var_by_name(self,i)
                if len(nodes_with_matching_names) is 0:
                    raise Exception(f"{i} not found in graph")
                else:
                    process_input_to_values[nodes_with_matching_names[0]] = inputs_to_values[i]
            else:
                process_input_to_values[i] = inputs_to_values[i]
        return process_input_to_values`
