### ISSUE TITLE
BUG (and potential solution): g++ not found when using pymc installed on Windows 11 using Python 3.11

### ISSUE THREAD

**Issue by jr-free** [pymc-devs/pytensor#234]
### Describe the issue:

Howdy folks,

Reporting this curious little hiccup discovered on a fresh pymc install on Windows 11, using Python 3.11, (mini)conda version 23.1.0. To be completely transparent, I followed the installation directions listed on the pymc page. Namely,

```
conda create -c conda-forge -n pymc_env "pymc>=4"
conda activate pymc_env
```

**The Issue**: 

As state in the title, g++ can't be located on my machine despite the m2w64 toolchain being installed and available in the environment. See attached `conda list` dump for verification. Attempting to import `pymc` and/or `pytensor` (in either terminal or jupyter notebook) yields the following familiar warning:

```
WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

That's about the size of it from an issue reporting standpoint. Doesn't break anything, but is a minor inconvenience as sampling time increases. That said, I spent some time last weekend exploring this and I believe I found a potential solution.

**Potential Solution**:  

Tracing the warning message back to the pytensor.configdefaults file (located in <conda dir>/site-packages/pytensor) I was able to focus in on the block of code starting on line 400 of that file (as of pytensor version 2.10.1) that begins

```
    try:
        rc = call_subprocess_Popen(["g++", "-v"])
    except OSError:
        rc = 1

...more stuff down here...
```

Tracing back to the `call_subprocess_Popen` function in utils.py. Some additional Sherlocking eventually points us to the `subprocess_Popen` located in the same file. This function contains some black magic that I can't even hazard an attempt to understand, *however* commenting out the line containing the statement `params["shell"] = True` appears to resolve the issue. 
See images below for additional context.

I can also confirm that sampling time is noticeably improved after removing that line, so I don't have reason to believe the effect silently remains. Additionally checking pytensor.config after import shows that the cxx attribute points to the g++ compiler in the pymc_env environment.

Anyway, that's what I got. Wanted to put it on the radar in case it helps anyone else. Might be worth exploring how reproducible this fix is if it regularly pops up for either Python 3.11 or Windows 11.

*Before commenting out.*
![image](https://user-images.githubusercontent.com/25798899/222915917-67d56f95-2242-462c-a81b-2288eb614007.png)

*After commenting out*
![image](https://user-images.githubusercontent.com/25798899/222915945-84b61180-e8a9-4e4e-b35c-fb4e674ed6d9.png)

*Pytensor config cxx attribute after commenting out*
![image](https://user-images.githubusercontent.com/25798899/222918371-5a26c4b1-585c-4a3f-a59f-6ad78ddbe401.png)

[pymc conda list dump.txt](https://github.com/pymc-devs/pymc/files/10889012/pymc.conda.list.dump.txt)

### Reproduceable code example:

```python
import pymc as pm
import pytensor
```

### Error message:

```shell
WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

### PyMC version information:

Followed official documentation for installation.

```
python: 3.11
pytensor: 2.10.1
pymc: 5.1.0
conda: 23.1.0
```

### Context for the issue:

It's an inconvenience to end-users using Windows 11 and Python 3.11 (assuming it's reproducible), hence it presents as a (minor) barrier to adoption of this most-excellent library.

### Edit:

Postscript: I apparently like to click buttons. Also, wanted to add additional context in the form of the value of the cxx attribute of pytensor.config prior to commenting `params['shell']=True` out. It is indeed empty, so we can rule out this being a case of the warnings just incorrectly being used without effect. Looks like g++ legitimately can't be found.

![image](https://user-images.githubusercontent.com/25798899/222919093-ff045113-01f0-4883-8705-0668b98115c6.png)

**Comment by twiecki** [comment]
Thanks for the great detective work, Sherlock @jr-free :), this is super valuable.

It seems the code in question was added by @michaelosthege: https://github.com/pymc-devs/pytensor/blame/63f8d6e732cd19e7f8940e25e4c44231e7765f96/pytensor/utils.py#L159 and it appears to have fixed some other Windows issue. One simple hack would be to find which versions of windows need it and which don't, or maybe try it with and without.

**Comment by michaelosthege** [comment]
In fact I did not add that code, but just moved it from another place in the codebase.

However, I noticed two things from your description:
1. You're using `conda` which should be fine in theory, but I strongly recommend using `mamba` instead (just `conda install -c conda-forge mamba` once in your base env). It is much faster and maybe it is also superior with dependency resolution.
2. You appear to be using a powershell command line. AFAIK this is not working nicely with environment activation. Try using Command Prompt. VS Code remembers the choice.

**Comment by jr-free** [comment]
Thanks for the speedy replies, gents.

I've been meaning to make the jump to mamba, so I'll take this as an opportunity to do so. I'll also see if using the vanilla command prompt yields different behavior.

An additional note: it appears my company computer -- which runs windows 10 and python 3.9 -- does not have this issue. To be sure, it *is* also running an older version of conda, but otherwise everything else for that machine was configured the same as above at essentially the same time (I.e. within a few days). All said seems like the root cause can be attributed back to one or more of:

1. Windows 11
2. Python 3.11
3. Conda
4. Command prompt vs. powershell
5. Aliens,

in order of completely arbitrary importance.

**Comment by loneguardian** [comment]
I would like to chip in on the "g++ not found error" discussion by providing my specs:

1. Windows 10
2. Python 3.11.3.final.0
3. Conda 23.5.0
4. Jupyter Notebook in VSCode 
![image](https://github.com/pymc-devs/pytensor/assets/803017/ed5d5b1b-d8fc-4095-9a2d-4445bdf1b161)
5. No aliens
