### ISSUE TITLE
BUG: Python package includes a lot of files it shouldn't

### ISSUE THREAD

**Issue by carlsmedstad** [pymc-devs/pytensor#243]
### Describe the issue:

The Python package contains a lot of files that aren't strictly required for the package. This causes problems when packaging for distributions (such as for Arch Linux in my case) as conflicts with other packages are likely to happen. Examples of files that should be removed from the package are the `doc/` and the `scripts/` directories.

This can be solved by removing `__init__.py` files from directories that aren't Python packages, adding excludes to `pyproject.toml` and by tweaking `MANIFEST.in`. Ideally the package should only contain the `pytensor/` directory.

It would also be a good idea to migrate the executable `pytensor-cache` into the `pytensor/` directory, and as such the pytensor package. This has been done in the original Aesara project.

Thanks!

### Reproducable code example:

```python
N/A
```

### PyTensor version information:

2.10.1

### Context for the issue:

I'm maintaining packages for PyMC and PyTensor for Arch Linux.

* https://aur.archlinux.org/packages/python-pymc
* https://aur.archlinux.org/packages/python-pytensor

**Comment by ricardoV94** [comment]
Thanks @carlsmedstad

**Comment by twiecki** [comment]
@carlsmedstad Thanks for reporting, would you be up to do a PR?

**Comment by carlsmedstad** [comment]
@twiecki I have a fairly clear idea of what needs to be done, so sure. No commitments as to when I will have time to do it though.
