### ISSUE TITLE
Don't customize rewrite names

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#247]
Rewrites can be optionally included or excluded based on their registered names. However, some of the registered names don't match the name of the rewrite function, which is shown with `optimizer_verbose=True`

For instance: 

```python
import pytensor
import pytensor.tensor as pt

seq = pt.vector("seq")
xs, _ = pytensor.scan(
  lambda s: pt.exp(s),
  sequences = [seq],
)

pytensor.config.optimizer_verbose=True
pytensor.function([seq], xs)
```
```
...
rewriting: rewrite push_out_seq_scan replaces for{cpu,scan_fn}.0 of for{cpu,scan_fn}(Subtensor{int64}.0, Subtensor{:int64:}.0, Subtensor{int64}.0) with Elemwise{exp,no_inplace}.0 of Elemwise{exp,no_inplace}(Subtensor{:int64:}.0)
...
```
You would think you can disable it, by excluding `push_out_seq_scan`, but that does not work
```python
from pytensor.compile.mode import get_mode

pytensor.function([seq], xs, mode=get_mode(None).excluding("push_out_seq_scan"))  
```
```
...
rewriting: rewrite push_out_seq_scan replaces for{cpu,scan_fn}.0 of for{cpu,scan_fn}(Subtensor{int64}.0, Subtensor{:int64:}.0, Subtensor{int64}.0) with Elemwise{exp,no_inplace}.0 of Elemwise{exp,no_inplace}(Subtensor{:int64:}.0)
...
``` 
Still there. Because it's actually registered with the name `scan_pushout_seqs_ops`:
https://github.com/pymc-devs/pytensor/blob/277559b411886c3dc1161cf197c5f250048ecec5/pytensor/scan/rewriting.py#L2486
```python
pytensor.function([seq], xs, mode=get_mode(None).excluding("scan_pushout_seqs_ops"))  
```
Now it's excluded!

We should register the rewrites with the same name of the function that is shown in the debug (easy) or find a way to show the registration name instead (possibly harder?).

**Comment by michaelraczycki** [comment]
I'd like to help with that

**Comment by ricardoV94** [comment]
That'd be great!
