### ISSUE TITLE
Use Numba Generators for random graphs and deprecate shared RandomState variables

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#316]
### Description

RandomState are legacy in numpy and we can save some complexity by letting go of them in PyTensor.

We were "obliged" to keep them because that's the only kind of RNG that Numba supported until now

**Comment by jessegrabowski** [comment]
I'm trying to understand this issue to start a PR. What actually needs to be done? Numba functions can take numpy random generators without any hassle now. For example, this works:

```python
import numba as nb
import numpy as np

@nb.njit
def draw_nb(rng, loc, scale, size):
    return rng.normal(loc=loc, scale=scale, size=size)

rng = np.random.default_rng()
draw_nb(rng, 0.0, 1.0, (10,))
```

So would it be enough to just chop out all of the extra machinery from `numba\dispatch\random.py` related to the random states [here](https://github.com/pymc-devs/pytensor/blob/0ebc83b393b7a3c310cdb451baee35b56b0dcc2f/pytensor/link/numba/dispatch/random.py#L25C1-L89C17)? Plus the check in `make_numba_random_fn`? Or is there something deeper going on.

Numba still doesn't support broadcasting from parameters, so all the rest of the machinery seems like it needs to say (though I personally find it quite difficult to follow, it would be nice to refactor it to be more clear).

**Comment by ricardoV94** [comment]
> Numba still doesn't support broadcasting from parameters, so all the rest of the machinery seems like it needs to say (though I personally find it quite difficult to follow, it would be nice to refactor it to be more clear).

This is the big hurdle. Generators without broadcasting is pretty useless so we have to support it if we want to really support RVs in numba backend (and phase out the RandomState)

**Comment by ricardoV94** [comment]
This is the PR where Generator support was added to Aesara. The main complexity is writing broadcasting logic with text which is the usual numba backend PITA.

**Comment by jessegrabowski** [comment]
But I'm saying I'm pretty sure you can directly plug a generator into what they already have? There's even a numba datatype for numpy random generators (`nb.types.NumPyRandomGenerator`)

**Comment by ricardoV94** [comment]
I think the only challenging is the broadcasting logic, which I think can't be written as a Python function without writing it for every Op?

I don't remember exactly where did things break.

Also the strict API for RVs requires copying the RNG if the Op is not inplace. Not sure if this is relevant.

**Comment by ricardoV94** [comment]
What did you mean, what we already had? Generators?

I remember our implementation being super hackish, we always change RandomState and don't respect seeding after the function is created. We would like to avoid that with the new Generator stuff

**Comment by ricardoV94** [comment]
Feel free to open a PR if you it seems like some minimal changes do the job (or even if they don't).

Unfortunately, I've lost the context to this issue to be able to help just from thinking

**Comment by jessegrabowski** [comment]
The broadcasting is done with a loop, so it's actually not too bad. Here is a basic sketch:

```python
import numba as nb
import numpy as np

@nb.njit
def draw_nb(rng, loc, scale, size):
    loc_bcast = np.broadcast_to(loc, size)
    scale_bcast = np.broadcast_to(scale, size)

    bcast_samples = np.empty(size, dtype=np.float64)
    
    for idx in np.ndindex(size):
        bcast_samples[idx] = rng.normal(loc_bcast[idx], scale_bcast[idx])
    return bcast_samples

rng = np.random.default_rng(1)
loc = np.zeros((5, 5))
scale = 1.0
size = (10, 5, 5)
samples_np = rng.normal(loc=loc, scale=scale, size=size)

rng = np.random.default_rng(1)
samples_nb = draw_nb(rng, loc, scale, size)

np.allclose(samples_np, samples_nb) #True
```

**Comment by ricardoV94** [comment]
Can you write that function in a way that works for any RV Op regardless of the number of parameters and ndim_supp/ndims_params?

I imagine that's the abstraction that complicates things.

**Comment by ricardoV94** [comment]
The box and unboxing of RandomState ia supposed to go out completely yes

**Comment by jessegrabowski** [comment]
No, you have to write overloads on a case-by-case basis

**Comment by ricardoV94** [comment]
It's also much more error prone though. For instance this is what the full function for NormalRV may look like:

```python
def normal_rv_dispatch(op, node):
  
  def normal(rng, size, dtype, loc, scale):
    if size is not None:
      loc, scale = np.broadcast_arrays(loc, scale)
        size = loc.shape
      else:
        loc = np.broadcast_to(loc, size)
        sigma = np.broadcast_to(sigma, size)
    
    if not op.inplace
      rng = copy(rng)

    out = np.empty(size, dtype=node.outputs[1].dtype
    
    # populate out

     return rng, out

  return normal
```

Can we use any helpers to avoid repeating all this boilerplate? Also it gets slightly more tricky with multivariate RVs or non scalar core parameters.

**Comment by jessegrabowski** [comment]
So I guess there are two issues being discussed here:

1. Can we eliminate the RandomStream objects and just use RandomGenerators (I think yes)
2. Does there need to be any changes to the numba overloads for RVs to make this happen (i think no, but it might be nice to think about anyway)

As I understand it, only issue (1) is causing problems. My motivation is to be able to use nutpie on any PyMC model -- currently I get an error about how random generators are not supported for some (I think scan based? But I don't have an example off the top of my head).

Anyway I'll open a PR that dumps the random streams and see what it breaks when I have some time.

**Comment by ricardoV94** [comment]
I also bet numba will complain about the use of size or something and perhaps require we define two functions depending on whether size is provided.

And probably size has to be converted to a fixed size tuple. Small things that add to more boilerplate. Then multiply that by all the RV ops we have between pytensor and PyMC.

For me unreadable string manipulation doesn't seem to bad in comparison. Maybe we can make it more readable even? 

Regardless, hopefully numba will just do the work and implement overloads properly -.-

**Comment by ricardoV94** [comment]
> Anyway I'll open a PR that dumps the random streams and see what it breaks when I have some time.

Thanks!
