### ISSUE TITLE
Revert patch for index underflow after location 127 when `mode=JAX`

### ISSUE THREAD

**Issue by jessegrabowski** [pymc-devs/pytensor#395]
### Describe the issue:

It seems the JAX linker downcasts index constants to `uint8`? `mode=None` and `mode="NUMBA"` work as expected. Declaring an index variable (`i = pt.lscalar('i'); z = x[i]`) also works as expected.

### Reproducable code example:

```python
import pytensor
import pytensor.tensor as pt
import numpy as np

x = pt.dvector('x')
z1 = x[127]
z2 = x[128]
f = pytensor.function([x], [z1, z2], mode='JAX')

f(np.arange(200))
# out: [Array(127., dtype=float64), Array(0., dtype=float64)]
```

### PyTensor version information:

Pytensor 2.13.1

**Comment by ricardoV94** [comment]
Now that I didn't expect xD

**Comment by jessegrabowski** [comment]
I think I was wrong though, it's casting to `int8` not `uint8` (int8 goes to 128. uint8 should go to 255). Wouldn't dropping the minus sign break negative indexes?

**Comment by ricardoV94** [comment]
I stepped on the debugger and it was keeping the same type as the one reported in the `dprint` of the compiled function. I didn't see any implicit casting, only the one done explicitly by the rewrite mentioned above.

**Comment by jessegrabowski** [comment]
I guess I'm asking why we rewrite to uint8 then? Isn't it needlessly restrictive?

**Comment by ricardoV94** [comment]
This was fixed in JAX, but may be worth waiting a while longer before reverting the patch
