### ISSUE TITLE
Get a new project logo

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pytensor#4]
We should replace the Aesara logo which is still shown on the README with a new logo that does not infringe the Aesara brand.

**Comment by fonnesbeck** [comment]
I will start a contest for this. My inclination is to ask for something that plays off of the PyMC logo thematically somehow (rockets, colors, etc.) to emphasize the link between the two libraries. OTOH we could go for something entirely different if that's what people want. Thoughts?

**Comment by michaelosthege** [comment]
closed by #142
