### ISSUE TITLE
DOC: Contributing link is broken

### ISSUE THREAD

**Issue by madt2709** [pymc-devs/pytensor#41]
### Issue with current documentation:

On the READ ME, the link to the [contributing guide](https://github.com/pymc-devs/pytensor/blob/main/README.rst#contributing): https://github.com/pymc-devs/pytensor/CONTRIBUTING.md is an empty page. 

Would be good to update the link/page with contributing guide. 

### Idea or request for content:

I guess it should point to this: https://pytensor.readthedocs.io/en/latest/dev_start_guide.html

**Comment by twiecki** [comment]
@madt2709 Thanks for the report. Want to do a PR? I think we can just copy over the pymc contributing guide.

**Comment by madt2709** [comment]
@twiecki could you please give me access? I can't currently assign the issue to myself or push my changes.

**Comment by twiecki** [comment]
You can just open a PR.
