### ISSUE TITLE
[Feature Request]: Add betaincinv and gammaincinv

### ISSUE THREAD

**Issue by amyoshino** [pymc-devs/pytensor#413]
### Context for the issue:

I would like to initiate this matter to formally request the inclusion of the following functions:
- `betaincinv`: Inverse of the regularized incomplete beta function, or quantile function for the beta distribution.
- `gammaincinv`: Inverse to the regularized lower incomplete gamma function.

The implementation of these functions will allow us to implement quantile/ICDF functions for distributions like Beta, Gamma, ChiSquared and StudentT distributions, being fundamental to the issue: https://github.com/pymc-devs/pymc/pull/6845

Some references I think might be useful:
- `betaincinv` function in SciPy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gammaincinv.html
- `gammaincinv` function  in SciPy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.betaincinv.html
- CEPHES implementation of betaincinv: https://github.com/scipy/scipy/blob/main/scipy/special/cephes/incbi.c
- CEPHES implementation of gammaincinv: https://github.com/scipy/scipy/blob/main/scipy/special/cephes/igami.c
- Very neat implementation of betaincinv for TensorFlow probability: https://github.com/tensorflow/probability/issues/1581

**Comment by ricardoV94** [comment]
That would be really nice. Would you like to take a stab at it?

**Comment by amyoshino** [comment]
Surely! I can definitely give it a shot! I'll need guidance along the way, and I'll update with a PR once I make progress. Thanks for your support!

**Comment by amyoshino** [comment]
I'd be more than happy to give it a try. I will require some guidance as I work on it, and I'll keep you posted with a pull request as soon as I make some headway. Your support is greatly appreciated!

**Comment by ricardoV94** [comment]
Happy to help and thanks in advance!
