### ISSUE TITLE
DOC: wrong indentation level in gradient.py `grad` `Lop` and `Rop`

### ISSUE THREAD

**Issue by hsinfan1996** [pymc-devs/pytensor#414]
### Issue with current documentation:
pytensor.gradient.grad
https://github.com/pymc-devs/pytensor/blob/686811ca809880238c2b89bb9b87965658838157/pytensor/gradient.py#L482-L488
pytensor.gradient.Lop
https://github.com/pymc-devs/pytensor/blob/686811ca809880238c2b89bb9b87965658838157/pytensor/gradient.py#L385-L392
pytensor.gradient.Rop
https://github.com/pymc-devs/pytensor/blob/686811ca809880238c2b89bb9b87965658838157/pytensor/gradient.py#L197-L204
### Idea or request for content:

Make it one indentation level less for the content of `Returns` and remove the extra blank line at the end (only for `grad`).

**Comment by ricardoV94** [comment]
Thanks, would you like to fix it yourself?

**Comment by hsinfan1996** [comment]
> Thanks, would you like to fix it yourself?

Yes.
