### ISSUE TITLE
BUG: using numpy code that has been deprecated in v1.26.0

### ISSUE THREAD

**Issue by jpreszler** [pymc-devs/pytensor#441]
### Describe the issue:

Numpy v1.26.0 was released on Sept. 16, 2023. It no longer has a `get_info()` method inside numpy.__config__ which is used https://github.com/pymc-devs/pytensor/blob/main/pytensor/link/c/cmodule.py#L2720. This causes package import to fail because pytensor doesn't have a upper limit on the version of numpy that can be loaded.

### Reproducable code example:

```python
# with numpy 1.26.0
import pytensor
```

### Error message:

```shell
import pytensor
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pytensor/__init__.py:119: in <module>
    from pytensor import scalar, tensor
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pytensor/tensor/__init__.py:106: in <module>
    from pytensor.tensor import (  # noqa
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pytensor/tensor/blas.py:102: in <module>
    from pytensor.tensor.blas_headers import blas_header_text, blas_header_version
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pytensor/tensor/blas_headers.py:1015: in <module>
    if not config.blas__ldflags:
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pytensor/configparser.py:321: in __get__
    val_str = self.default()
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pytensor/link/c/cmodule.py:2720: in default_blas_ldflags
    blas_info = np.__config__.get_info("blas_opt")
E   AttributeError: module 'numpy.__config__' has no attribute 'get_info'
Error: Process completed with exit code 4.
```

### PyTensor version information:

pytensor v2.16.1

**Comment by maresb** [comment]
While we have not yet solved the compatibility of PyTensor and NumPy v1.26.0, we have constrained our conda-forge packages so that new environments should enforce NumPy with <1.26.0, preventing the error from occurring.

**Comment by brendan-m-murphy** [comment]
I get the same error if I compile numpy 1.25.2 using meson. (I think in numpy 1.26, uses the meson build by default.)

In the meson build of numpy 1.25.2, the `__config__.py` file is a different style and doesn't have a `get_info` function. So this isn't really 1.26 vs 1.25, it's meson vs. the old build process.

**Comment by johannes-mueller** [comment]
> While we have not yet solved the compatibility of PyTensor and NumPy v1.26.0, we have constrained our conda-forge packages so that new environments should enforce NumPy with <1.26.0, preventing the error from occurring.

That has the disadvantage that pytensor seems not to be installable for Python 3.12 as numpy<1.26 seems not to be installable on Python 3.12
