### ISSUE TITLE
Extend support to Python 3.12

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#472]
### Description

Current blocker: https://github.com/pymc-devs/pytensor/pull/444

**Comment by ricardoV94** [comment]
#444 was closed. We can run the CI on 3.12 and lift the pin in setup.py (or wherever it is) to see if tests pass

**Comment by twiecki** [comment]
@maresb Is this something you're able to help with?

**Comment by maresb** [comment]
Ya, should I start a PR?

**Comment by ricardoV94** [comment]
> Ya, should I start a PR?

Sarcasm: https://www.pymc.io/projects/docs/en/latest/contributing/pr_tutorial.html

(Yes)

**Comment by ricardoV94** [comment]
@maresb @lucianopaz anything blocking 3.12?

**Comment by maresb** [comment]
Hmm, I don't know, I lost track of this a bit. I'll try rebasing #488 to see what happens.
