### ISSUE TITLE
Implement equivalent to `numpy.nan_to_num`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#479]
### Description

A couple of switches should do the job, no need to implement a new Op

https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html

**Comment by priyankavgalagali** [comment]
import numpy as np
example_array = np.array([np.nan, 1, np.inf, -np.inf, 3], dtype=float)

nan_replace = -1
posinf_replace = 1000
neginf_replace = -1000
import numpy as np

def custom_nan_to_num(arr, nan_val=0.0, posinf_val=None, neginf_val=None):
    if posinf_val is None:
        posinf_val = np.finfo(arr.dtype).max
    if neginf_val is None:
        neginf_val = np.finfo(arr.dtype).min

    # Using np.where to replace values based on condition
    arr = np.where(np.isnan(arr), nan_val, arr)
    arr = np.where(np.isposinf(arr), posinf_val, arr)
    arr = np.where(np.isneginf(arr), neginf_val, arr)

    return arr

# Apply the custom function
result = custom_nan_to_num(example_array, nan_val=nan_replace, 
                           posinf_val=posinf_replace, 
                           neginf_val=neginf_replace)

print(result)

Im new to this.....Can you let me if its somethis like this or the function of numpy.nan_to_num is to be replaced?
