### ISSUE TITLE
BUG: Numpy is still pinned

### ISSUE THREAD

**Issue by carlsmedstad** [pymc-devs/pytensor#491]
### Describe the issue:

Numpy was unpinned but the requirements for build-system was missed: https://github.com/pymc-devs/pytensor/blob/0f802ab2ddb5f960218f88d1e984417cdbe94bc8/pyproject.toml#L5

Had to apply the following patch for my AUR package to be buildable:

```diff
--- pyproject.toml	2023-11-12 20:35:07.203052447 +0100
+++ pyproject.toml	2023-11-12 20:35:25.833092070 +0100
@@ -2,7 +2,7 @@
 requires = [
   "setuptools>=48.0.0",
   "cython",
-  "numpy>=1.17.0,<1.26",
+  "numpy>=1.17.0",
   "versioneer[toml]>=0.28",
 ]
 build-backend = "setuptools.build_meta"
```

### Reproducable code example:

```python
N/A
```

### Error message:

```shell
N/A
```

### PyTensor version information:

2.17.4

### Context for the issue:

I maintain the [AUR package](https://aur.archlinux.org/packages/python-pytensor) for PyTensor.

**Comment by twiecki** [comment]
Good catch, want to do a PR for the fix?

**Comment by maresb** [comment]
Thanks @carlsmedstad for the sharp eye!
