### ISSUE TITLE
Accelerate the CI pipeline

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pytensor#5]
Right now the CI is taking ~1.5 h.

However, we can split up jobs in the job matrix to parallelize more, and also investigate whether we're unnecessarily running things multiple times (e.g. different Python versions).

Maybe the [`scripts/check_all_tests_are_covered.py`](https://github.com/pymc-devs/pymc/blob/main/scripts/check_all_tests_are_covered.py) from PyMC can be adapted to quickly diagnose redundacies?

**Comment by danhphan** [comment]
Hi @michaelosthege, let me work on this one :) Thanks!

**Comment by ricardoV94** [comment]
I think GitHub CI is running the tests marked as slow, one failed recently. That could explain why they take so long

**Comment by danhphan** [comment]
Yes, good points, I will look into it in details this weekend. Sorry for the delay :)

**Comment by ricardoV94** [comment]
The runslow seems to be on purpose:

https://github.com/pymc-devs/pytensor/blob/19e1a982e5a2e9ba2bd9d708133abf102c6fb835/.github/workflows/test.yml#L135

**Comment by danhphan** [comment]
Yes, the `--runslow` is used to run `pytest` on tests with `@pytest.mark.slow` decorator. All these `slow` tests are currently run on both python version 3.7 and 3.9. Running these slow tests on only one python version (3.9) should reduce CI running time.

I'm also looking into detail to see how to break these tests into smaller parts similar to PyMC workflows `tests.yml`

**Comment by danhphan** [comment]
It seems that most slow tests are from `tests/tensor/test_math.py` and `tests/tensor/test_basic.py`, so I'm going to separate these two test files. 

![Screenshot from 2022-12-18 19-04-34](https://user-images.githubusercontent.com/25697956/208287770-eda4873e-d0ae-43ed-98ab-25187e657860.png)

**Comment by ricardoV94** [comment]
Closed via #176
