### ISSUE TITLE
BLAS warning on Windows builds on conda-forge

### ISSUE THREAD

**Issue by maresb** [pymc-devs/pytensor#515]
### Description

```python
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

See [the logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=829292&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=623c2ba8-c4f1-582d-6c78-1c7699e2e0a2&l=1897).

I'm going to add some more debug commands to try and get more info.

**Comment by ricardoV94** [comment]
Possibly related to #508

**Comment by ricardoV94** [comment]
By the way that should be a blocker not to cut a release in conda-forge

**Comment by maresb** [comment]
To clarify: no conda-forge release until we resolve this warning. Agreed.

**Comment by maresb** [comment]
The info is now available: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=829473&view=logs&jobId=171a126d-c574-5c8c-1269-ff3b989e923d&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=623c2ba8-c4f1-582d-6c78-1c7699e2e0a2

Looks like `blas__ldflags` is empty/unset.

**Comment by ricardoV94** [comment]
Yeah same issue. CC poor @lucianopaz

**Comment by lucianopaz** [comment]
I dug into this issue. It looks like [conda stores](https://docs.conda.io/projects/conda-build/en/stable/user-guide/environment-variables.html) libraries for windows stuff in a different folder. I think that we can fix the problem by simply including the `CONDA_PREFIX\Library\bin` and `CONDA_PREFIX\Library\lib` into the library search directories.

That means that #508 is not related to this issue.
