### ISSUE TITLE
ENH: Implement exponentially scaled modified Bessel function Op

### ISSUE THREAD

**Issue by dehorsley** [pymc-devs/pytensor#542]
### Before

```python
pt.iv(J, a) / pt.exp(a)
```

### After

```python
pt.ive(J, a)
```

### Context for the issue:

Periodic HSGPs (now in PyMC 🥳 ) require `iv(J, a) / exp(a)` as normalizing factor. Using this directly could lead to overflows however (as `iv` grows like `exp(x)`). Instead `ive(nu,x) = iv(nu,x) / exp(abs(x))` exists, and as a bonus cheaper to compute than the combined!

After #403 we already have an implementation of `ive` in JAX, and it's in [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ive.html), so should be straightforward!

**Comment by maresb** [comment]
Woah, this is wild. Literally 5 minutes ago I was trying to normalize a periodicized Gaussian and ran into this exact expression.

I'll defer to Ricardo regarding the implementation, but would be very grateful for a reference for this normalization, either in code or literature. (I'm just screwing around in Mathematica.)

**Comment by ricardoV94** [comment]
> Woah, this is wild. Literally 5 minutes ago I was trying to normalize a periodicized Gaussian and ran into this exact expression.
> 
> I'll defer to Ricardo regarding the implementation, but would be very grateful for a reference for this normalization, either in code or literature. (I'm just screwing around in Mathematica.)

Scipy docstrings are not too bad

**Comment by maresb** [comment]
Sorry, I should have been more specific. I'm looking to see how else `ive` arises as a normalization factor, or if the HSGP stuff is normalizing the exact same function as me.

**Comment by dehorsley** [comment]
@maresb [Solin & Särkkä 2014](http://proceedings.mlr.press/v33/solin14.pdf) is where I learnt it form

**Comment by maresb** [comment]
Awesome, thanks @dehorsley!!!

Indeed I was normalizing exactly (23), so it's great to connect this with the literature.
