### ISSUE TITLE
Add tensor helper equivalent for `scipy.special.logit`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#563]
### Description

Currently missing: https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.logit.html#scipy.special.logit

Should not require a new Op, a simple function with existing PyTensor ops would suffiec

**Comment by HarshvirSandhu** [comment]
@ricardoV94 
I would like to work on this.
Please let me know where this function should be

**Comment by ricardoV94** [comment]
In tensor.special
