### ISSUE TITLE
Implement `einsum` equivalent

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#57]
### Please describe the purpose of filing this issue

Probably quite some work, but would be nice to have an equivalent: https://numpy.org/doc/stable/reference/generated/numpy.einsum.html

If we want to support the C backend:
https://numpy.org/devdocs/reference/c-api/array.html#c.PyArray_EinsteinSum

@aseyboldt previously linked to: https://optimized-einsum.readthedocs.io/en/stable/backends.html

**Comment by ricardoV94** [comment]
The `Op` itself would be challenging to write, not so much the dispatch to other frameworks

**Comment by twiecki** [comment]
Why? It would just take a string and pass that through?

**Comment by ricardoV94** [comment]
You need to specify the input output types, and gradients and a few more stuff to make it not worse than the current manual alternatives.
