### ISSUE TITLE
FEAT: JAX Conversion for the given SortOp

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#595]
### Description

 NotImplementedError: No JAX conversion for the given `Op`: SortOp{quicksort, None}

**Comment by HarshvirSandhu** [comment]
I would like to work on this

**Comment by HarshvirSandhu** [comment]
@twiecki 
Should the implementation and tests be added with the basic tensor functionalities([here](https://github.com/pymc-devs/pytensor/blob/main/pytensor/link/jax/dispatch/basic.py)) and tests ([here](https://github.com/pymc-devs/pytensor/blob/main/tests/link/jax/test_tensor_basic.py))?

**Comment by twiecki** [comment]
> @twiecki Should the implementation and tests be added with the basic tensor functionalities([here](https://github.com/pymc-devs/pytensor/blob/main/pytensor/link/jax/dispatch/basic.py)) and tests ([here](https://github.com/pymc-devs/pytensor/blob/main/tests/link/jax/test_tensor_basic.py))?

Yes I believe that's where it should go.
