### ISSUE TITLE
Add pre-commit-ci hook

### ISSUE THREAD

**Issue by maresb** [pymc-devs/pytensor#599]
We don't currently have any automatic mechanism for updating the version tags in `.pre-commit-config.yaml`. I think that we should use https://github.com/marketplace/pre-commit-ci. I think this should be straightforward for @ricardoV94 to enable.

EDIT: Strange... GitHub mangled my initial description, so I had to rewrite the above. :disappointed:

**Comment by ricardoV94** [comment]
@juanitorduz @maresb is this one taken care of?

**Comment by maresb** [comment]
I think I just enabled it:

![image](https://github.com/pymc-devs/pytensor/assets/15216687/3b14de51-5e50-47fa-b979-153319de2876)

**Comment by maresb** [comment]
Yes! 

I restarted CI on #596 and it showed up:

![image](https://github.com/pymc-devs/pytensor/assets/15216687/90f0fb1d-be0e-4cbf-9169-000088806ca1)

Also, it's showing up under [installed apps](https://github.com/pymc-devs/pytensor/settings/installations)

**Comment by juanitorduz** [comment]
@maresb great! Could you help us with PyMC marketing? https://github.com/pymc-labs/pymc-marketing/pull/476 What else do we need to do to make it work ?

**Comment by juanitorduz** [comment]
@ricardoV94 @twiecki I think we need to give access to the app from the pymc-labs account right?
