### ISSUE TITLE
Decide and impose a hard line limit

### ISSUE THREAD

**Issue by maresb** [pymc-devs/pytensor#610]
### Description

Despite reviewing #586 I'm only now realizing that we have an ignore on `E501` "line too long".

The formatter will reformat lines to have width 88 when automatically possible, but there doesn't seem to be any other mechanism for complaining about long lines that can't be autoformatted. Is this accidental or deliberate?

My concern is that without a hard line limit, long lines tend to accumulate in a codebase, and then it becomes a huge chore if you want to fix them at some point.

**Comment by ricardoV94** [comment]
We can add but perhaps not 88. What's the norm these days 120?

**Comment by maresb** [comment]
I personally use 88 and almost all projects I know also use 88. My main motivation is that diffs with long lines are hard to read, especially on a laptop screen. 

If it doesn't bother you then probably it's not a problem. The problem is only when you want a limit but it's not enforced.

**Comment by ricardoV94** [comment]
We can have a limit I am not against it. I thought we had one already.

Just find 88 very restrictive

**Comment by maresb** [comment]
Ok, I will look into this soon. We can start with a very long hard limit and reduce it to taste.

**Comment by lucianopaz** [comment]
I think that the ignore was added to ignore long lines in docstrings. The auto-formatter will fix the code part that gets long lines, but doesn't deal with long strings or multi line strings like docstrings. Sometimes, it's good for docstrings to be long lines (specially when you add tables or fancy markdown things in the middle), so it's ok to have the ignore in those cases

**Comment by ricardoV94** [comment]
From the last comment I concluded this was not a problem. Feel free to reopen if I misinterpreted
