### ISSUE TITLE
Argument name is incorrect

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#64]
https://github.com/pymc-devs/pytensor/blob/6c4d66c7679f2b323c8e6dc880b8b797cc0dc442/pytensor/graph/basic.py#L1618

The second argument name should be `f_apply`, not `f_node`. This is semantically will be more correct and will follow the dicstring

**Comment by sudarsan2k5** [comment]
Hi @ferrine I would like to work on this.

**Comment by twiecki** [comment]
Great @sudarsan2k5, just open a PR and we'll be happy to review!
