### ISSUE TITLE
Bug: `linalg.kron` is not correct for matrices of `ndims > 2`

### ISSUE THREAD

**Issue by jessegrabowski** [pymc-devs/pytensor#640]
### Description

See these discussions:
- https://github.com/pymc-devs/pytensor/pull/622
- https://github.com/scipy/scipy/issues/20072

The fix is easy enough, we just have to switch from the scipy implementation to the numpy implementation. We can follow the JAX implementation [here](https://github.com/google/jax/blob/9352a00dab3c465a4e2c651cc6a0fa91e50ae7a2/jax/_src/numpy/lax_numpy.py#L3797).

An alternative would be to keep our implementation, but `BlockWise` it so that the `ndim > 2` case just broadcasts over the additional dimensions. It would make us equivalent to `jax.vmap(jnp.kron)(A, B)` by default.

**Comment by ricardoV94** [comment]
We should do like numpy. Batching can be done with vectorize.

**Comment by ilayn** [comment]
Hi all, apologies for the terse response I had yesterday, busy with multiple PRs at the same time. Would you like the nd support per se from scipy or numpy is good enough already for your use cases? 

It is not difficult to get this over the line for me, I just need to understand the use cases if there are any edge cases that you want it to be addressed.

**Comment by ilayn** [comment]
There might be also some convention math vs. code issues that might arise if you have empty arrays like `np.empty([0, 2, 2])` etc. to preserve dimensions and so on. Hence it would be great to know what your expectations are from those cases

**Comment by jessegrabowski** [comment]
Hi @ilayn -- thanks for following up. We're not actually interested in empty arrays, just in making sure tensor kroneckers come out correctly. The way it originally came up was in the context of #622. We found that the scipy implementation doesn't respect commutativity with unary linear algebra functions like `cholesky` and `inv`. That is, we expected `inv(kron(A, B))` to be the same as `kron(inv(A), inv(B))`. The scipy implementation doesn't respect this, while the numpy one does, which led to our concerns about the implementation.

**Comment by ilayn** [comment]
Yes that's because nd arrays are not supported and actually some einsum magic might even be more appropriate than any kron implementation since this is a quite intensive operation. Typically there is some strange overlap between numpy.linalg and scipy.linalg for historical reasons and I'm not even sure why we have it on the scipy side. I would use numpy kron anyways since this is pretty much an array operation and relies on the basic data movement with a mul instead number crunching.

**Comment by jessegrabowski** [comment]
Awesome, thanks for verifying.

**Comment by tanish1729** [comment]
hey jesse! continuing what i started on discourse, for this PR i understand that the kronecker product function from scipy does not work for n-d arrays but only for 2d arrays. thats why there is a need to use the numpy implementation instead? 
if that is correct, please let me know how should that be reflected in the code so i can start working.

like you said there is very less time left, I will try to close this issue soon and then have a discussion about the main project of all the rewrites

**Comment by jessegrabowski** [comment]
Kron should be written in pure pytensor; you can see how it currently looks [here](https://github.com/pymc-devs/pytensor/blob/f97d9ea306fb7f006a35a83280c664fdc3242700/pytensor/tensor/slinalg.py#L562). I call this the "scipy implementation" because it follows the code inside `scipy.linalg.kron` found [here](https://github.com/scipy/scipy/blob/53467c8f3cbd5af234625f9effb9a0fde88dfb8a/scipy/linalg/_special_matrices.py#L307).

As we discovered, this code is not valid for tensors of dimension greater than 2, so we need to switch to following how numpy does the computation. Actually I suggest we switch to following the JAX implementation I linked above. Basically a PR needs to:

1. Remove the `kron` function from `pytensor.tensor.slinag`
2. Add a new `kron` function to `pytensor.tensor.nlinalg`, copying the JAX implementation. It can keep the docstring as-is, only the computation needs to change
3. Verify that the current tests still pass
4. Add a new test for the case of kron(3d, 3d)

**Comment by tanish1729** [comment]
oh great i get it. 
just an unrelated query - what are the 2 different files `slinalg` and `nlinalg` supposed to be for.

once i am done making the new function, should i open a new PR for the same?
