### ISSUE TITLE
Remove `list_of_nodes` in favor of similar `applys_between`

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#65]
### Description

https://github.com/pymc-devs/pytensor/blob/main/pytensor/graph/basic.py#L951
and
https://github.com/pymc-devs/pytensor/blob/main/pytensor/graph/basic.py#L1589

**Comment by ricardoV94** [comment]
The second link is pointing to a different function than the one you mentioned `list_of_nodes`

**Comment by ferrine** [comment]
updated

**Comment by ricardoV94** [comment]
list_of_nodes is only used in one place and I think it can be safely replaced by the applys_between
