### ISSUE TITLE
Implement matrix_transpose and mT method for TensorVariables

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#677]
### Description

Numpy 2.0 is introducing these, we should also. We already have the function implemented internally in a bunch of places when doing rewrites with Blockwise Ops.

https://numpy.org/devdocs/release/2.0.0-notes.html#matrix-transpose-support-for-ndarrays

Under the hood it would be a simple `swapaxes(self, -1, -2)`

**Comment by Dhruvanshu-Joshi** [comment]
Hi @ricardoV94 
I would like to work on it. This is the rough implementation of numpy's matrix_transpose function:
```
import numpy as np
x = ptb.as_tensor_variable(x)
if x.ndim < 2:
        raise ValueError(
            f"Input array must be at least 2-dimensional, but it is {x.ndim}"
        )
return np.swapaxes(x, -1, -2)
```
I don't know yet if numpy's swapaxes will work with tensor variable.  Will work on swapaxes (which based on my understanding will be based on Dimshuffle) also if it does not. Which module do you think this should go under?

**Comment by ricardoV94** [comment]
You can and should use `pt.swapaxes`. The function should go into tensor/basic probably. It has most of these trivial helpers in it.
