### ISSUE TITLE
Add `name` keyword argument to `Op.__call__`

### ISSUE THREAD

**Issue by jessegrabowski** [pymc-devs/pytensor#685]
### Description

Allow arbitrary `Op`s to be given names. It's a nice way to keep dprints readable and code tidy. Here's what I imagine:

Before:

```
x = pt.tensor('x', shape=(None,))
y = pt.tensor('y', shape=(None,))
z = pt.add(x, y)
z.name = 'z'
```

After:

```
x = pt.tensor('x', shape=(None,))
y = pt.tensor('y', shape=(None,))
z = pt.add(x, y, name='z')
```

**Comment by HarshvirSandhu** [comment]
I would like to work on this

**Comment by ricardoV94** [comment]
You don't need to change the dprint. 

The behavior to look for is that `z.name == "z"` after your changes. 

In the dprint, it will look slightly different for z, as it is not a root variable. It will show it to the right

**Comment by ricardoV94** [comment]
Feel free to work on it @HarshvirSandhu
