### ISSUE TITLE
Add helper function to find all inputs needed to a compile a graph

### ISSUE THREAD

**Issue by jessegrabowski** [pymc-devs/pytensor#695]
### Description

It'd be nice to have a tool to automatically make the required inputs to a function. The function already exists in PyMC as [`pymc.pytensorf.inputvars`](https://github.com/pymc-devs/pymc/blob/5f95fc292adebbeb31b6de825b7b407042e382fd/pymc/pytensorf.py#L230), but I think this should be in pytensor itself. 

There's also `pytensor.graph.basic.graph_inputs`, but this returns constants and shared variables. Given an arbitrary graph `z`, I'd like to be able to do `f = pytensor.function(get_input_vars(z), z)`.

**Comment by ricardoV94** [comment]
As suggested let's call it `get_required_inputs` to distinguish from the existing one
