### ISSUE TITLE
DOC: Installation instructions in the developer start guide outdated

### ISSUE THREAD

**Issue by Dhruvanshu-Joshi** [pymc-devs/pytensor#696]
### Issue with current documentation:

The current documentation for the ```dev_start_guide``` directs contributors to run the following commands:
https://github.com/pymc-devs/pytensor/blob/30b760f26366eda7ea26edb1993e521b9d6d55c8/doc/dev_start_guide.rst?plain=1#L176-L179
https://github.com/pymc-devs/pytensor/blob/30b760f26366eda7ea26edb1993e521b9d6d55c8/doc/dev_start_guide.rst?plain=1#L208-L211
However, we have long dropped the use of ```requirements.txt``` and ```requirements-rtd.txt``` and hence this needs to be rectified.

**Comment by ricardoV94** [comment]
Yup, instructions should you conda + environment.yml I think
