### ISSUE TITLE
`pt.specify_broadcastable` does not work with negative axis values

### ISSUE THREAD

**Issue by tomicapretto** [pymc-devs/pytensor#698]
### Description

If I use `pt.specify_broadcastable` with the second argument equal to `-1` it does not do anything. It needs the value of the axis in order to work. See the example:

```python
import pytensor.tensor as pt

tensor = pt.tensor(shape=(5, 1), broadcastable=(False, False))
print(tensor.broadcastable)

tensor2 = pt.specify_broadcastable(tensor, -1)
print(tensor2.broadcastable)

tensor3 = pt.specify_broadcastable(tensor, 1)
print(tensor3.broadcastable)
```
```
(False, False)
(False, False)
(False, True)
```

I'm using PyTensor version 2.20.0

**Comment by Dhruvanshu-Joshi** [comment]
What is the behaviour expected when axis is set to -1? I believe it should set the last dimension as broadcastable right? Or do we want to return an error?

**Comment by ricardoV94** [comment]
> What is the behaviour expected when axis is set to -1? I believe it should set the last dimension as broadcastable right? Or do we want to return an error?

The first. There's a numpy helper used throughout the library to normalize axis, that converts negative ones to positive based on the input ndim
