### ISSUE TITLE
Don't fail when squeezing specific non-broadcastable axis

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#705]
### Description

The following snippet fails:

```python
import pytensor.tensor as pt

x = pt.vector("x")
pt.squeeze(x, axis=0)
# ValueError: Cannot drop a non-broadcastable dimension: [False], []
```

The user provided us information that this dimension will be of length 1, so we could add a `specify_broadcastable` and only then call `squeeze`. I think this behavior is more intuitive, and I don't see any drawbacks.

This can only be done when the user provides specific axis, not when axis=None

```python
pt.squeeze(pt.specify_broadcastable(x, 0), axis=0).eval({x: [0]}) 
# array(0.)
pt.squeeze(pt.specify_broadcastable(x, 0), axis=0).eval({x: [0, 1, 2]})
# AssertionError: SpecifyShape: dim 0 of input has shape 3, expected 1.
```

**Comment by Dhruvanshu-Joshi** [comment]
So here we'll have to first make the axis(given it is not None) broadcastable manually in the ```pt.squeeze``` function itself is what is to be done?

**Comment by ricardoV94** [comment]
Yeah, but only if it's not already broadcastable (in which case it would be useless)
