### ISSUE TITLE
Seems like Numpy has dropped python 3.7 in v1.23.5

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pytensor#76]
### Description

https://github.com/numpy/numpy/blob/v1.23.5/setup.py#L453

**Comment by ricardoV94** [comment]
Yeah, we are always a dragged slightly down by Google Colab lagging behind. We should test with Python 3.11 though

**Comment by ferrine** [comment]
pandas has also dropped
https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L24

**Comment by aseyboldt** [comment]
I think numba doesn't support py11 yet, but we could still test everything except the numba code.
