### ISSUE TITLE
Don't run mypy in pre-commit

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pytensor#768]
### Description

It's too slow, let it run in the CI

**Comment by HangenYuu** [comment]
As I read the documentation,
1. There are tag [`skip`](https://pre-commit.ci/#configuration-skip) for hook to be skipped in CI, but no tag for hook to be run only in CI.
2. There is tag [`stages`](https://pre-commit.com/index.html#confining-hooks-to-run-at-certain-stages) to confine hook to a certain stage only.

The way I look at it, you want pre-commit run as a [GitHub Action](https://github.com/marketplace/actions/pre-commit) only and not locally?

**Comment by ricardoV94** [comment]
You can probably use the pymc as a template: https://github.com/pymc-devs/pymc/blob/main/.github%2Fworkflows%2Fmypy.yml
