### ISSUE TITLE
Consider using pr-labeler-action

### ISSUE THREAD

**Issue by maresb** [pymc-devs/pytensor#801]
### Description

It's very mildly annoying to remember (and often forget) the `no releasenotes` label on stuff like pre-commit-ci. Unfortunately labels are not supported by pre-commit.ci. A suggested workaround is to [use pr-labeler-action](https://github.com/pre-commit-ci/issues/issues/24#issuecomment-732315853) to add the label.

I'm leaning towards this not being worthwhile since adding the label is not actually cumbersome, and it probably doesn't justify adding a new GHA workflow. Unless it could be used for more purposes.

Feel free to close without comment, I'm just using this issue to communicate my findings.

#### EDIT: My description above was truncated to the first paragraph! I wonder what caused that, because that could cause significant loss of work.

**Comment by maresb** [comment]
Based on #802 and #803 it seems like I hit a one-off GitHub glitch with the truncation. Still fairly unsettling.

**Comment by ricardoV94** [comment]
pre-commit-ci is really annoying. Dependabot adds the label automatically.

**Comment by maresb** [comment]
In a lot of instances it's really convenient, but ya, for PyMC stuff we've had a lot of weird issues with it. Do you think we should switch back to GHA?

**Comment by ricardoV94** [comment]
> In a lot of instances it's really convenient, but ya, for PyMC stuff we've had a lot of weird issues with it. Do you think we should switch back to GHA?

I don't remember, what does pre-commit do better? Speed?

**Comment by maresb** [comment]
It's tough to remember exactly, but off the top of my head...

Speed, yes, which does sometimes come in handy when making a PR and you get quicker feedback when something's off.

It's the more managed option, so no need to maintain a GHA workflow. For most projects it just works.

I'm inclined to just keep it as-is, but in case you do get frustrated then switching back to GHA is viable.

**Comment by ricardoV94** [comment]
I'm okay with it. My message above was a bit dramatic :)

**Comment by maresb** [comment]
Decided to keep things as-is.
