### ISSUE TITLE
ENH: implement JAX modified Bessel function via exponentially modified version

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pytensor#91]
The modified Bessel function of the first kind is not currently available in Jax, but there is an exponentially-scaled version such that:

    ive(v, z) = iv(v, z) * exp(-abs(z.real))

However `ive` is not available in PyTensor. Implementing it would allow us to have `iv` from this transformation.

### Context for the issue:

The Bessel functions are useful in places like the Hilbert space approximation kernels for GPs. It would be valuable to be able to sample these with the Jax backend for performance reasons.

**Comment by ricardoV94** [comment]
There are two things. We can easily add an `ive` helper to `pytensor.tensor`.

Separately from that, if you want to use `iv` in JAX we can use the (JAX) `ive` in the JAX dispatch of `iv`. Only issue is we need to add tensorflow probability as a dependency? Also I haven't tried to use it with JAX, so I don't know exactly what it requires. 

I believe @ColCarroll might have some pointers?

**Comment by fonnesbeck** [comment]
Another big one we are missing is the error function `erfc` which keeps us from using the normal CDF. There's no JAX implementation either, so we could go the TF route there too.

**Comment by twiecki** [comment]
Couldn't we copy it over from tfp?
